from __future__ import annotations

# Dataclass utilities
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class RetrievedItem:
    """
    One retrieved evidence item from a grounding source.
    """

    # Retrieval source name
    source: str

    # Human-readable content
    content: str

    # Optional structured payload
    metadata: Dict[str, Any] = field(default_factory=dict)

    # Optional score
    score: Optional[float] = None

    # Optional reference URI / URL / identifier
    reference: Optional[str] = None


@dataclass
class GroundingRequest:
    """
    Standard grounding request used by NeoOLAF layers.
    """

    # Layer name requesting grounding
    layer_name: str

    # Main query string
    query: str

    # Optional query payload
    payload: Dict[str, Any] = field(default_factory=dict)

    # Preferred retrieval spaces
    preferred_sources: List[str] = field(default_factory=list)

    # Number of items to retrieve per source
    top_k: int = 5


@dataclass
class GroundingResult:
    """
    Final grounding result returned to a NeoOLAF layer.
    """

    # Original request
    request: GroundingRequest

    # Chosen retrieval sources
    selected_sources: List[str] = field(default_factory=list)

    # Retrieved evidence
    retrieved_items: List[RetrievedItem] = field(default_factory=list)

    # Grounding summary generated by the agentic workflow
    grounding_summary: str = ""

    # Optional structured aggregation
    merged_context: Dict[str, Any] = field(default_factory=dict)